services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:photografedi@localhost:5432/photografedi
      - UPLOAD_DIR=/app/uploads
      - STORAGE=local # set to 's3' to use S3FileRepository
      - S3_BUCKET= # your-s3-bucket
      - S3_REGION=us-east-1
      - S3_BASE_URL= # optional public base url for objects
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "bun install && bun run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - BUN_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped
    command: sh -c "bun install && bun run dev"

  db:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: photografedi

volumes:
  pg_data:
